### ISSUE TITLE
Improve current implementation of the arduino socket io bridge

### ISSUE THREAD

**Issue by chaos-adept** [spaceshipyard/mars-rover-android-socketio-bridge#4]
so far an Android service is used to listen to the [dispatcher](https://github.com/spaceshipyard/mars-rover-dispatcher) events and making a call.
it was written in a quick and dirty way.

in order to improve it, it makes sense to do the next steps:

- [x] investigate how to start skype over adb
- [x] investigate how to install and connect adb from the Raspberrian OS to the target device
- [x] investigate how to call adb from the nodejs (it is optional and it might be de-scoped)

**Comment by vnabatov** [comment]
as was discussed 
we can use adb here and connect phone to the raspberry pi

**Comment by chaos-adept** [comment]
@0ff53t0r 
Could we as the first step in this task investigate how to call skype from adb?

for information so far there is the following pure java example:
https://github.com/spaceshipyard/mars-rover-android-socketio-bridge/blob/master/app/src/main/java/com/chaoslabgames/mars/bridge/remote/socketio/ArduinoBridgeService.java#L200
```
        private void makeCall(String participants, boolean video) {
            Intent skype = new Intent("android.intent.action.VIEW");
            skype.setData(Uri.parse("skype:" + participants + "?call" + (video ? "&video" : "")));
            skype.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
            startActivity(skype);
```

**Comment by 0ff53t0r** [comment]
i was able to start call on skype through adb with the command:
adb shell am start -a android.intent.action.VIEW -d skype:echo123?call --activity-clear-top

**Comment by chaos-adept** [comment]
@0ff53t0r 
it is great!
Do you have a raspberry device to work on the next step - `investigate how to install and connect adb from the Raspberrian OS to the target device`?

**Comment by chaos-adept** [comment]
@0ff53t0r  up
+ could you provide a link to the protocol that you mentioned?

**Comment by 0ff53t0r** [comment]
i have a raspberry to continue investigation.
protocol is [mqtt](https://github.com/mqtt/mqtt.github.io/wiki)

**Comment by 0ff53t0r** [comment]
i have used [adbkit ](https://github.com/openstf/adbkit) for Node.js on raspberry. it requires adb-server to be installed.
i used the floowing commands:
`sudo apt-get install -y android-tools-adb android-tools-fastboot`
`npm install --save adbkit`

once installed i have connected my android to raspberry with debug mode on and started adb server with 
`pi@raspberrypi:~ $ adb start-server`
then I ran the following skype.js script to check:
[skype.zip](https://github.com/spaceshipyard/mars-rover-android-socketio-bridge/files/2063519/skype.zip)
i have run the script with the command:
`pi@raspberrypi:~ $ DEBUG=adb:* node skype.js`
skype opened on my android and started video call to echo

**Comment by chaos-adept** [comment]
it is great, https://github.com/spaceshipyard/mars-rover-node-bridge/issues/16 has been raised to integrate results of this research into node bridge.
